"""
srm_bridge.py

Formats raw MCTS planner output into a strict, minimal JSON payload that can be
handed directly to the local LLM (Qwen 0.5B) for natural-language rendering.

Architecture role
─────────────────
  MCTSPlanner.search()
        │
        ▼
  SRMBridge.generate_payload()   ← pure Python logic, zero model calls
        │
        ▼
  JSON string  ──►  Qwen 0.5B   (renders into human-readable prose)
        │
        └──────►  Logging / Dashboard (raw structured data)

Design principles
──────────────────
  • The JSON schema is intentionally tiny — every field must earn its place.
  • All reasoning strings are generated by deterministic Python rules so the
    LLM's only job is prose rendering, not reasoning. This keeps the LLM
    call trivially fast and prevents hallucination of market facts.
  • The payload is self-contained: a reader with no prior context can
    understand the decision.
  • All numeric fields are pre-formatted as strings so the JSON parses
    identically on any platform (no float precision surprises).
"""

from __future__ import annotations

import json
import time
from datetime import datetime, timezone
from typing import Any

# ──────────────────────────────────────────────────────────────────────────────
# Thresholds (tunable)
# ──────────────────────────────────────────────────────────────────────────────

ENTROPY_HIGH_THRESHOLD   = 5.0   # bits — above this: "HIGH",  MCTS budget large
ENTROPY_MEDIUM_THRESHOLD = 2.0   # bits — above this: "MEDIUM"
                                  #          below:    "LOW"

CONFIDENCE_STRONG  = 0.20        # Q-value difference vs 2nd choice to call "strong"
CONFIDENCE_WEAK    = 0.05        # Below this: "weak"

SELF_LOOP_THRESHOLD = 0.90       # Probability above which a symbol is "trapped"

ACTION_LABELS = {0: "HOLD", 1: "BUY", 2: "SELL"}


# ──────────────────────────────────────────────────────────────────────────────
# Helpers
# ──────────────────────────────────────────────────────────────────────────────

def _entropy_band(entropy: float) -> str:
    if entropy >= ENTROPY_HIGH_THRESHOLD:
        return "HIGH"
    if entropy >= ENTROPY_MEDIUM_THRESHOLD:
        return "MEDIUM"
    return "LOW"


def _confidence_word(q_best: float, q_second: float) -> str:
    """Describe the margin between the best and second-best action."""
    margin = q_best - q_second
    if margin >= CONFIDENCE_STRONG:
        return "strong"
    if margin >= CONFIDENCE_WEAK:
        return "moderate"
    return "weak"


def _build_reasoning(
    symbol:          int,
    entropy:         float,
    action:          int,
    q_values:        dict[int, float],    # {action_id: Q-value}
    simulations:     int,
    top_transitions: list[tuple[int, float, int]],  # [(next_sym, prob, count), …]
    icm_reward:      float | None = None,
) -> str:
    """
    Generate a deterministic, rule-based reasoning narrative from MCTS outputs.

    Rules are applied in order;  relevant fragments are concatenated.
    """
    parts: list[str] = []
    band = _entropy_band(entropy)

    # ── 1. Market state characterisation ──────────────────────────────────────
    if band == "HIGH":
        parts.append(
            f"High-entropy symbol #{symbol:04d} ({entropy:.2f} bits): "
            f"next market state is broadly uncertain across many symbols."
        )
    elif band == "MEDIUM":
        parts.append(
            f"Medium-entropy symbol #{symbol:04d} ({entropy:.2f} bits): "
            f"market shows moderate branching with a few dominant transitions."
        )
    else:
        parts.append(
            f"Low-entropy symbol #{symbol:04d} ({entropy:.2f} bits): "
            f"market is in a near-deterministic regime."
        )

    # ── 2. Transition structure observation ───────────────────────────────────
    if top_transitions:
        top_sym, top_prob, _ = top_transitions[0]
        self_loop = (top_sym == symbol)

        if self_loop and top_prob >= SELF_LOOP_THRESHOLD:
            parts.append(
                f"Dominant self-loop detected: {top_prob:.0%} probability of "
                f"remaining in #{symbol:04d} (stasis regime)."
            )
        elif self_loop:
            parts.append(
                f"Partial self-loop: {top_prob:.0%} chance of staying in "
                f"#{symbol:04d}, remainder disperses to {len(top_transitions)-1} "
                f"successor states."
            )
        else:
            parts.append(
                f"Most likely successor is #{top_sym:04d} ({top_prob:.1%}), "
                f"suggesting a directional market move."
            )

    # ── 3. ICM curiosity signal ────────────────────────────────────────────────
    if icm_reward is not None:
        if icm_reward > 1.5:
            parts.append(
                f"ICM curiosity reward is high ({icm_reward:.3f}): "
                f"this transition is out-of-distribution for the forward model — "
                f"treat this decision with elevated uncertainty."
            )
        elif icm_reward > 0.8:
            parts.append(
                f"ICM curiosity reward is moderate ({icm_reward:.3f}): "
                f"forward model has partial familiarity with this regime."
            )
        else:
            parts.append(
                f"ICM curiosity reward is low ({icm_reward:.3f}): "
                f"forward model is well-calibrated on this state."
            )

    # ── 4. Action selection rationale ─────────────────────────────────────────
    q_sorted = sorted(q_values.items(), key=lambda kv: kv[1], reverse=True)
    best_a, best_q = q_sorted[0]
    label = ACTION_LABELS.get(action, str(action))

    if len(q_sorted) >= 2:
        _, second_q = q_sorted[1]
        conf_word   = _confidence_word(best_q, second_q)
        margin      = best_q - second_q
        parts.append(
            f"MCTS selected {label} with {conf_word} confidence "
            f"(Q={best_q:+.4f}, margin over next-best: {margin:+.4f}) "
            f"across {simulations:,} simulations."
        )
    else:
        parts.append(
            f"MCTS selected {label} (Q={best_q:+.4f}) "
            f"across {simulations:,} simulations."
        )

    # ── 5. Action-specific risk notes ─────────────────────────────────────────
    if action == 1:   # BUY
        if band == "HIGH":
            parts.append(
                "Caution: BUY in a high-entropy regime carries elevated "
                "slippage risk due to wide next-state dispersion."
            )
        else:
            parts.append(
                "BUY signal is consistent with a directional or recovering market."
            )
    elif action == 2:  # SELL
        if band == "LOW":
            parts.append(
                "SELL in a low-entropy (stasis) regime may indicate "
                "mean-reversion opportunity or defensive exit."
            )
        else:
            parts.append(
                "SELL signal reflects the planner's preference to reduce "
                "exposure in the current regime."
            )
    else:              # HOLD
        if band == "HIGH":
            parts.append(
                "HOLD is the risk-minimising choice under high uncertainty: "
                "avoid committing capital until the regime resolves."
            )
        elif top_transitions and top_transitions[0][0] == symbol and \
                top_transitions[0][1] >= SELF_LOOP_THRESHOLD:
            parts.append(
                "HOLD aligns with the stasis regime: "
                "high probability of remaining in current state makes "
                "entering or exiting a position costly."
            )
        else:
            parts.append(
                "HOLD reflects marginal Q-value advantage: "
                "the planner sees no sufficiently rewarded entry/exit opportunity."
            )

    return " ".join(parts)


# ──────────────────────────────────────────────────────────────────────────────
# SRMBridge
# ──────────────────────────────────────────────────────────────────────────────

class SRMBridge:
    """
    Converts MCTS planner output into a self-contained JSON decision payload.

    The payload is designed to be:
      1. Passed to a local LLM (Qwen 0.5B) for natural-language narration.
      2. Logged directly as structured data for dashboards / replay.
      3. Human-readable on its own without any additional context.

    Parameters
    ----------
    include_timestamp : bool
        Append a UTC ISO-8601 timestamp to each payload.  Default: True.
    indent : int | None
        JSON indentation spaces.  Use None for compact single-line output
        (saves ~30% bytes when logging at high frequency).  Default: 2.
    """

    def __init__(
        self,
        include_timestamp: bool = True,
        indent:            int | None = 2,
    ) -> None:
        self.include_timestamp = include_timestamp
        self.indent            = indent

    def generate_payload(
        self,
        symbol:          int,
        entropy:         float,
        action:          int,
        q_values:        dict[int, float],
        simulations:     int,
        top_transitions: list[tuple[int, float, int]] | None = None,
        icm_reward:      float | None = None,
        extra:           dict[str, Any] | None = None,
    ) -> str:
        """
        Build and return the decision JSON string.

        Parameters
        ----------
        symbol : int
            Current market symbol ID (from SymbolicQuantizer).
        entropy : float
            Shannon entropy of the current symbol (bits).
        action : int
            Chosen action: 0=HOLD, 1=BUY, 2=SELL.
        q_values : dict[int, float]
            Mapping from action_id to mean reward (Q-value) for each action.
            Example: {0: +0.102, 1: -0.044, 2: +0.031}
        simulations : int
            Number of MCTS simulations run for this decision.
        top_transitions : list of (next_symbol, probability, count) | None
            Top probable next states from MarketTransitionGraph.
            If None, transition reasoning is omitted.
        icm_reward : float | None
            Intrinsic curiosity reward for the last observed transition.
            If None, ICM reasoning is omitted.
        extra : dict | None
            Any additional key-value pairs to append verbatim to the payload.
            Useful for raw_price, tick_index, tape_name etc.

        Returns
        -------
        str : JSON-encoded decision payload.
        """
        band        = _entropy_band(entropy)
        action_name = ACTION_LABELS.get(action, str(action))

        # Best Q-value for the chosen action
        best_q      = q_values.get(action, 0.0)

        # Ranked action table for the payload
        ranked_actions = [
            {
                "action":  ACTION_LABELS.get(a, str(a)),
                "q_value": f"{q:+.4f}",
                "chosen":  (a == action),
            }
            for a, q in sorted(q_values.items(), key=lambda kv: kv[1], reverse=True)
        ]

        # Build reasoning narrative via Python rules (no LLM)
        reasoning = _build_reasoning(
            symbol          = symbol,
            entropy         = entropy,
            action          = action,
            q_values        = q_values,
            simulations     = simulations,
            top_transitions = top_transitions or [],
            icm_reward      = icm_reward,
        )

        # Core payload schema
        payload: dict[str, Any] = {
            "current_symbol":      f"#{symbol:04d}",
            "market_entropy":      f"{band} ({entropy:.2f} bits)",
            "simulations_run":     simulations,
            "decision":            action_name,
            "confidence_q_value":  f"{best_q:+.4f}",
            "action_rankings":     ranked_actions,
            "reasoning":           reasoning,
        }

        # Optional fields
        if top_transitions:
            payload["top_next_states"] = [
                {
                    "symbol":      f"#{t[0]:04d}",
                    "probability": f"{t[1]:.2%}",
                    "obs_count":   t[2],
                }
                for t in top_transitions[:3]
            ]

        if icm_reward is not None:
            payload["icm_curiosity_reward"] = f"{icm_reward:.4f}"

        if self.include_timestamp:
            payload["timestamp_utc"] = datetime.now(timezone.utc).strftime(
                "%Y-%m-%dT%H:%M:%SZ"
            )

        if extra:
            payload.update(extra)

        return json.dumps(payload, indent=self.indent, ensure_ascii=False)

    def generate_from_mcts(
        self,
        planner,          # MCTSPlanner instance
        symbol:     int,
        graph,            # MarketTransitionGraph instance
        icm_reward: float | None = None,
        extra:      dict[str, Any] | None = None,
    ) -> str:
        """
        Convenience wrapper that reads directly from a live MCTSPlanner instance
        after search() has been called.

        Parameters
        ----------
        planner    : MCTSPlanner — must have _last_root populated (post-search).
        symbol     : int          — root symbol that was searched.
        graph      : MarketTransitionGraph — for top_transitions lookup.
        icm_reward : float | None — ICM reward for current tick, if available.
        extra      : dict | None  — verbatim fields to append.

        Returns
        -------
        str : JSON payload
        """
        root = planner._last_root
        if root is None:
            raise RuntimeError("Run planner.search() before calling generate_from_mcts().")

        # Extract Q-values from MCTS root children
        q_values: dict[int, float] = {
            a: node.Q for a, node in root.children.items()
        }

        # Top transitions from graph
        top_transitions = graph.get_probabilities(symbol, top_k=3)

        # Determine best action
        action = max(q_values, key=lambda a: q_values[a]) if q_values else 0

        return self.generate_payload(
            symbol          = symbol,
            entropy         = graph.symbol_entropy(symbol),
            action          = action,
            q_values        = q_values,
            simulations     = planner._last_n_sims,
            top_transitions = top_transitions,
            icm_reward      = icm_reward,
            extra           = extra,
        )

    def slim_payload(self, full_payload: str) -> str:
        """
        Strip verbose fields from a full payload JSON string, returning a
        compact version suitable for the local LLM's limited context window.

        Removed fields:
          * 'reasoning'       — pre-written by Python rules; LLM should derive
                                its own narration from the raw facts.
          * 'action_rankings' — detailed Q-table is redundant for prose rendering.
          * 'timestamp_utc'   — not needed for narration.

        The slim payload averages ~350-400 chars versus ~1100 for the full one,
        cutting token usage by ~65% and staying safely under a 512-token ctx.

        Parameters
        ----------
        full_payload : str
            JSON string from generate_payload() or generate_from_mcts().

        Returns
        -------
        str : compact JSON string with only the essential facts.
        """
        STRIP_FIELDS = {"reasoning", "action_rankings", "timestamp_utc"}
        data = json.loads(full_payload)
        slim = {k: v for k, v in data.items() if k not in STRIP_FIELDS}
        return json.dumps(slim, indent=self.indent, ensure_ascii=False)

    def __repr__(self) -> str:
        return (
            f"SRMBridge("
            f"timestamp={self.include_timestamp}, "
            f"indent={self.indent})"
        )


# ──────────────────────────────────────────────────────────────────────────────
# Execution block
# ──────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":

    bridge = SRMBridge(include_timestamp=True, indent=2)

    # ── Test 1: Hardcoded payload matching prior MCTS output ──────────────────
    # These values come directly from our MCTS run on Symbol #000199:
    #   entropy=7.559, 694 sims, HOLD=best (Q=+0.1417),
    #   BUY=Q=-0.0214, SELL=Q=+0.0869
    print("=" * 64)
    print("  Test 1 — Exact MCTS outputs from Symbol #0199 run")
    print("=" * 64)

    payload_199 = bridge.generate_payload(
        symbol      = 199,
        entropy     = 7.559,
        action      = 0,           # HOLD
        q_values    = {0: +0.1417, 1: -0.0214, 2: +0.0869},
        simulations = 694,
        top_transitions = [
            (337, 0.01816, 17),
            (294, 0.01816, 17),
            (68,  0.01816, 17),
        ],
        icm_reward  = 1.843,
        extra       = {
            "tape":       "market_tape_volatile-bear-dump-stable_2026-02-23_16-54-01.jsonl",
            "tick_index": 91,
        },
    )
    print(payload_199)

    # ── Test 2: Low-entropy stasis symbol (#0243) ─────────────────────────────
    print("\n" + "=" * 64)
    print("  Test 2 — Low-entropy stasis Symbol #0243")
    print("=" * 64)

    payload_243 = bridge.generate_payload(
        symbol      = 243,
        entropy     = 0.326,
        action      = 2,           # SELL
        q_values    = {0: -0.3963, 1: -0.3967, 2: -0.0108},
        simulations = 77,
        top_transitions = [
            (243, 0.9699,  7266),  # strong self-loop
            (166, 0.00320,   24),
            (205, 0.00294,   22),
        ],
        icm_reward  = 0.214,
    )
    print(payload_243)

    # ── Test 3: Medium-entropy oscillation (#0317) ────────────────────────────
    print("\n" + "=" * 64)
    print("  Test 3 — Medium-entropy oscillation Symbol #0317")
    print("=" * 64)

    payload_317 = bridge.generate_payload(
        symbol      = 317,
        entropy     = 5.877,
        action      = 0,           # HOLD
        q_values    = {0: +0.0419, 1: -0.1436, 2: +0.0152},
        simulations = 539,
        top_transitions = [
            (116, 0.0656, 17),
            (486, 0.0656, 17),
            (337, 0.0579, 15),
        ],
        icm_reward  = 0.921,
    )
    print(payload_317)

    # ── Test 4: Compact (no indent) for high-freq logging ──────────────────────
    print("\n" + "=" * 64)
    print("  Test 4 — Compact single-line payload (for log streaming)")
    print("=" * 64)

    bridge_compact = SRMBridge(include_timestamp=False, indent=None)
    compact = bridge_compact.generate_payload(
        symbol      = 199,
        entropy     = 7.559,
        action      = 0,
        q_values    = {0: +0.1417, 1: -0.0214, 2: +0.0869},
        simulations = 694,
    )
    print(compact)
    print(f"\n  Bytes: {len(compact.encode())}")

    # ── Test 5: Live integration with MCTSPlanner ──────────────────────────────
    print("\n" + "=" * 64)
    print("  Test 5 — Live MCTSPlanner + SRMBridge integration")
    print("=" * 64)

    from pathlib import Path
    from srm_quantizer import SymbolicQuantizer
    from srm_transition_graph import MarketTransitionGraph
    from srm_mcts import MCTSPlanner
    from srm_environment import SRMEnvironment

    QUANT_PATH = Path(__file__).parent / "srm_quantizer_512.pkl"
    GRAPH_PATH = Path(__file__).parent / "srm_graph_512.pkl"

    q     = SymbolicQuantizer.load(QUANT_PATH)
    graph = MarketTransitionGraph.load(GRAPH_PATH, q)
    planner = MCTSPlanner(graph=graph, quantizer=q, base_simulations=150)

    env   = SRMEnvironment(
        Path(__file__).parent /
        "solana-tapes/market_tape_volatile-bear-dump-stable_2026-02-23_16-54-01.jsonl"
    )
    state, info = env.reset()

    # Skip to a tick where a bin shift occurs (more interesting state)
    for _ in range(89):
        state, _, done, _, info = env.step(0)
        if done: break

    sym = q.encode(state)
    print(f"\n  Running MCTS on live tape tick {info['tick_index']} — Symbol #{sym:04d} …")

    action, root = planner.search(sym)

    live_payload = bridge.generate_from_mcts(
        planner    = planner,
        symbol     = sym,
        graph      = graph,
        icm_reward = 0.743,
        extra      = {
            "tick_index":  info["tick_index"],
            "raw_price":   f"${info['activePrice']:.4f}",
            "elapsed_ms":  f"{planner._last_elapsed_ms:.1f}",
        },
    )
    print(live_payload)

    print("\n✅  SRMBridge operational.")
    print("    Pass the JSON string to Qwen 0.5B with a prompt like:")
    print('    "You are a trading assistant. Convert this JSON into one clear sentence."')
